(define (problem FCR)
  (:domain FCR)
  (:objects southbank - southbank northbank - northbank wolf - wolf goat - goat cabbage - cabbage boat - boat farmer - farmer)
  (:init (empty_boat boat)
         (at wolf southbank)
         (at goat southbank)
         (at cabbage southbank)
         (at farmer southbank)
         (at_bank boat southbank))
  (:goal (and 
              (at wolf northbank)
              (at goat northbank)
              (at cabbage northbank)
              (at farmer northbank)
              (at_bank boat northbank)))
)