(define (problem blocksworld-11-1)
(:domain blocksworld)
(:objects b c e a h k i g d f j )
(:init (clear j) (clear f) (clear d) (clear g) (on-table i) (on-table k)
 (on-table h) (on-table a) (on j i) (on f e) (on e k) (on d c) (on c h) (on g b)
 (on b a) (arm-free))
(:goal (and (on b d) (on d j) (on j k) (on k h) (on h a) (on a c) (on c f) (on f g) (on g i) (on i e))))