(define (problem blocksworld-4-2)
(:domain blocksworld)
(:objects b d c a )
(:init (clear a) (clear c) (clear d) (on-table a) (on-table b) (on-table d)
 (on c b) (arm-free))
(:goal (and (on a b) (on b c) (on c d))))