(define (problem blocksworld-25-0)
(:domain blocksworld)
(:objects l n t k i m q j g y w d o h s r c v e f b p x u a )
(:init (clear a) (clear u) (clear x) (clear p) (on-table b) (on-table f)
 (on-table e) (on-table p) (on a v) (on v c) (on c r) (on r s) (on s h) (on h o)
 (on o d) (on d w) (on w y) (on y g) (on g j) (on j q) (on q m) (on m b)
 (on u i) (on i k) (on k t) (on t f) (on x n) (on n l) (on l e) (arm-free))
(:goal (and (on l t) (on t w) (on w n) (on n o) (on o s) (on s y) (on y a) (on a r) (on r c) (on c g) (on g j) (on j d) (on d b) (on b k) (on k p) (on p m) (on m x) (on x e) (on e v) (on v f) (on f i) (on i q) (on q h) (on h u))))