(define (domain PUZZLE)
  (:requirements :strips)
  (:predicates (tile ?t)
               (position ?p)
               (at ?t ?p)
               (adjacentu ?from ?emp)
               (adjacentd ?from ?emp)
               (adjacentl ?from ?emp)
               (adjacentr ?from ?emp)
               (empty ?emp)
  )
  
  (:action move-left
    :parameters (?t ?from ?emp)
    :precondition (and (tile ?t) (position ?from) (position ?emp)
                       (adjacentl ?from ?emp) (at ?t ?from) (empty ?emp))
    :effect (and (not (at ?t ?from)) (not (empty ?emp))
                 (at ?t ?emp) (empty ?from))
  )
  (:action move-right
    :parameters (?t ?from ?emp)
    :precondition (and (tile ?t) (position ?from) (position ?emp)
                       (adjacentr ?from ?emp) (at ?t ?from) (empty ?emp))
    :effect (and (not (at ?t ?from)) (not (empty ?emp))
                 (at ?t ?emp) (empty ?from))
  )
  (:action move-up
    :parameters (?t ?from ?emp)
    :precondition (and (tile ?t) (position ?from) (position ?emp)
                       (adjacentu ?from ?emp) (at ?t ?from) (empty ?emp))
    :effect (and (not (at ?t ?from)) (not (empty ?emp))
                 (at ?t ?emp) (empty ?from))
  )
  (:action move-down
    :parameters (?t ?from ?emp)
    :precondition (and (tile ?t) (position ?from) (position ?emp)
                       (adjacentd ?from ?emp) (at ?t ?from) (empty ?emp))
    :effect (and (not (at ?t ?from)) (not (empty ?emp))
                 (at ?t ?emp) (empty ?from))
  )
  
)